version: "3.7"

services:
  server:
    labels:
      - "traefik.backend=${TRAEFIK_BACKEND}"
      - "traefik.docker.network=prod"
      - "traefik.frontend.rule=Host:${TRAEFIK_URL}"
      - "traefik.enable=true"
    networks:
      - default
      - prod
    depends_on:
      - db

networks:
  prod:
    external: true
    name: ${TRAEFIK_NETWORK}
